# Generated by Django 5.2.1 on 2025-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_files',
            field=models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lecture_files',
            field=models.FileField(blank=True, null=True, upload_to='lectures/%Y/%m/%d/'),
        ),
    ]
