# Generated by Django 5.2.1 on 2025-05-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_assignment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='teacher',
        ),
    ]
