# Generated by Django 5.2.1 on 2025-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_lecture_url_lesson_submission_url_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment_file_field_name',
            field=models.CharField(blank=True, help_text='Назва поля для завантаження файлу роботи студента', max_length=200, null=True),
        ),
    ]
