# Generated by Django 5.2.1 on 2025-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_studentassignmentsubmission_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Коментар викладача'),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оцінка'),
        ),
    ]
