# Generated by Django 5.2.1 on 2025-05-11 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_studentassignmentsubmission_feedback_and_more'),
        ('courses', '0007_lesson_assignment_file_field_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentassignmentsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='certificate_issued',
            field=models.BooleanField(default=False, verbose_name='Сертифікат видано'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterUniqueTogether(
            name='studentassignmentsubmission',
            unique_together={('student', 'lesson')},
        ),
    ]
